### ISSUE TITLE
awesome gem, but was unable to find the method I was seeking (Array#product)

### ISSUE THREAD

**Issue by ngouy** [jbodah/suggest_rb#6]
and finally found
![image](https://user-images.githubusercontent.com/12391171/57398232-8616f880-719c-11e9-9467-2eff3b85df52.png)

**Comment by jbodah** [comment]
`:args` expects an array of arguments. In your example, `product` is called with one argument `[1]` so `:args` should be `[[1]]` (as the first arg is an array)

```
$ ruby -rsuggest -e 'puts [1,2,3].what_returns? [[1,1],[2,1],[3,1]], args: [[1]]'
product
```

**Comment by ngouy** [comment]
haha ^^ my bad . sorry for the inconvenience 🙏

**Comment by jbodah** [comment]
No worries :+1:
